;;; init.el --- Initialization file for Emacs -*- lexical-binding: t; -*-
(message "[ Start (user: %s) ]" (user-login-name))
(message "[ Setup packages ]")
(load (concat user-emacs-directory "packages.el"))
(message "[ Configure behaviour ]")
(load (concat user-emacs-directory "config.el"))
(message "[ Setup key-bindings ]")
(load (concat user-emacs-directory "keybind.el"))
(message "[ Update appearance ]")
(load (concat user-emacs-directory "appearance.el"))
(when (display-graphic-p)
  (message "[ Update graphic appearance ]")
  (load (concat user-emacs-directory "appearance-graphic.el")))
